---
- hosts: app_nodes
  become: yes
  vars:
    APP_NAME: flaskapp
    REPOSITORY_URL: https://github.com/jkanclerz/example-flask-app-1
  tasks:
    - name: "install os packages"
      yum:
        name: python3, python3-pip, git
    - name: "git clone repo"
      git:
        repo: "{{REPOSITORY_URL}}"
        dest: "/opt/{{APP_NAME}}"
    - name: "create user"
      user:
        name: "{{APP_NAME}}"
    - name: "create venv"
      pip:
        virtualenv_command: python3 -m venv
        requirements: "/opt/{{APP_NAME}}/requirements.txt"
        virtualenv: "/opt/{{APP_NAME}}/.venv"
    - name: "put systemd config"
      template:
        src: flaskapp.service
        dest: "/etc/systemd/system/{{APP_NAME}}.service"
    - name: "start service"
      systemd:
        daemon_reload: yes 
        name: "{{APP_NAME}}"
        state: restarted
- hosts: lb_nodes
  become: yes
  vars:
    app_ips:
      - 172.31.2.56:80
      - 172.31.13.168:80
  tasks:
    - name: "install epel repo"
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
    - name: "install nginx"
      yum:
        name: nginx
        state: present
    - name: "install nginx conf"
      template:
        src: lb.conf
        dest: /etc/nginx/conf.d/blog.conf
    - name: "reload nginx"
      systemd:
        name: nginx
        state: reloaded


  
